src/contactify/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^', include('pages.urls', namespace="pages")),
  url(r'^contacts/', include('contacts.urls', namespace="contacts"))
]

src/contacts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.index, name="index")
]

src/pages/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
  url(r'^$', views.home, name="home")
]

src/contacts/models.py
from django.db import models

class Contact(models.Model):
  name       = models.CharField(max_length=120)
  address    = models.CharField(max_length=120)
  phone      = models.CharField(max_length=120)
  email      = models.CharField(max_length=120)
  is_active  = models.BooleanField(default=True)
  timestamp  = models.DateTimeField(auto_now_add=True)
  updated    = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.name

class Tag(models.Model):
  contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
  name    = models.CharField(max_length=120)

src/pages/models.py
from django.db import models

# Create your models here.

src/contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Contact

# Create your views here.
def index(request):
  all_contacts = Contact.objects.order_by('-updated')
  return render(request, 'contacts/index.html', {'contacts': all_contacts})

def detail(request):
  return HttpResponse('Contacts list')

src/pages/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
  return render(request, 'pages/home.html', {})

src/contacts/templates/contacts/index.html
{% extends "base.html" %}
{% block head_title %}Welcome || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>All Contacts</h1>
<ul>
{% for contact in contacts %}
  <li>{{ contact.name }} | {{ contact.address }}</li>
  <p>{{contact.phone}}, {{contact.email}}</p>
{% endfor %}
</ul>

{% endblock content %}

src/pages/templates/pages/home.html
{% extends "base.html" %}
{% block head_title %}Welcome || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Welcome</h1>

{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang=en>
<head>
  <title>{% block head_title %} Contactify {% endblock head_title %}</title>
  {% include "snippets/css.html" %}
</head>
<body>
  {% include "snippets/nav.html" %}

  <div class="container">
    {% block content %}
      Hello there
    {% endblock content %}
  </div>
</body>

</html>

src/templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<div class="container">
  <a class='navbar-brand' href="{% url 'pages:home' %}">Contactify</a>
  <a class="btn btn-primary" href="{% url 'contacts:index' %}">All Contacts</a>
</div>
<br/>